# -- coding: utf-8 --
"""myfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e-V4gddIhN9kVunjOiHNkcsxjzHTuap
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from streamlit_option_menu import option_menu

# Configuración de la página de Streamlit
st.set_page_config(page_title="Deforestación en Áreas Naturales Protegidas", page_icon="🌳", initial_sidebar_state="expanded", layout='wide')

# Cargar datos
archivo = "Dataset_DeforestacionAnp_SERNANP.csv"
data = pd.read_csv(archivo)

# Configuración del menú
with st.sidebar:
    menu = option_menu(
        menu_title="Menú Principal",
        options=["Inicio", "Gráficos", "Data", "Comparativo", "Zonificación"],
        icons=["house", "bar-chart", "table", "line-chart", "map"],
        menu_icon="menu-app",
        default_index=0
    )

# Sección: Inicio
if menu == "Inicio":
    st.title('Huellas de la deforestación')
    st.header("Rastreando el impacto de la pérdida forestal en Perú a través del tiempo")
    st.write("La deforestación en Perú es un fenómeno alarmante...")
    st.write("En este caso, analizaremos un registro de monitoreo...")

# Sección: Gráficos
if menu == "Gráficos":
    st.header("Gráficos de Deforestación")
    seleccion_anio = st.selectbox("Selecciona el año para mostrar el gráfico", [2021, 2022, 2023])
    
    # Función para procesar y filtrar datos
    def procesar_datos_por_anio(data, anio):
        meses = {1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril', 5: 'Mayo', 6: 'Junio',
                 7: 'Julio', 8: 'Agosto', 9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'}
        datos_anio = data[data['ANIO_REPORTE'] == anio]
        area_por_mes = datos_anio.groupby('MES_IMAG')['AREA_DEFO'].sum().reset_index()
        area_por_mes['MES_NOMBRE'] = area_por_mes['MES_IMAG'].map(meses)
        return area_por_mes, datos_anio
    
    # Mostrar gráficos según selección de año
    def graficos_y_tabla(data_anio, datos_filtrados, anio, color):
        st.write(f"Gráfico del área deforestada por mes en {anio}:")
        fig, ax = plt.subplots()
        ax.plot(data_anio['MES_NOMBRE'], data_anio['AREA_DEFO'], marker='o', color=color)
        ax.set_title(f'Área deforestada por mes en {anio}')
        ax.set_xlabel('Mes')
        ax.set_ylabel('Área Deforestada (ha)')
        ax.grid(True)
        plt.xticks(rotation=45)
        st.pyplot(fig)
        st.write(f"Datos filtrados para el año {anio}:")
        st.dataframe(datos_filtrados[['MES_IMAG', 'ANIO_REPORTE', 'AREA_DEFO']])
    
    data_anio, datos_filtrados = procesar_datos_por_anio(data, seleccion_anio)
    color = {'2021': 'orange', '2022': 'green', '2023': 'blue'}[str(seleccion_anio)]
    graficos_y_tabla(data_anio, datos_filtrados, seleccion_anio, color)

# Sección: Data
if menu == "Data":
    st.header("Vista completa de los datos")
    st.write("Tabla con todos los datos del registro:")
    st.dataframe(data)

# Sección: Comparativo
if menu == "Comparativo":
    st.header("Comparación entre Años")
    promedios = pd.DataFrame({
        "Año": ["2021", "2022", "2023"],
        "Promedio Mensual (ha)": [
            data[data['ANIO_REPORTE'] == 2021]['AREA_DEFO'].mean(),
            data[data['ANIO_REPORTE'] == 2022]['AREA_DEFO'].mean(),
            data[data['ANIO_REPORTE'] == 2023]['AREA_DEFO'].mean()
        ]
    })

    fig, ax = plt.subplots()
    ax.bar(promedios['Año'], promedios['Promedio Mensual (ha)'], color=['orange', 'green', 'blue'])
    ax.set_title('Promedio mensual de área deforestada (2021-2023)')
   


